name: update_deps

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  update_deps:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Install golang
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Checkout git repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          go install golang.org/x/perf/cmd/benchstat@latest && \
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && \
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest && \
          openssl req -x509 -newkey rsa:4096 -sha256 -days 365 -nodes -keyout example.key -out example.crt -subj "/CN=localhost" -addext "subjectAltName = DNS:localhost" && \
          protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative grpcapi/*.proto
      - name: Commit changes and create PR if we have any changes
        run: bash .github/update_deps.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: fix/autoupdate_dependencies
          REPO_NAME: ${{ github.repository }}
          REPO_OWNER: ${{ github.repository_owner }}
